#!/bin/bash
# (until we get automake/autoconf configured right.)

set -e

TESTDIR="$(dirname "$0")"

cd "$TESTDIR"
set -- ./test*

for TEST
do
	if "$TEST"
	then
		printf "%s\tOK\n" "$TEST"
	else
		printf "%s\tFAILED\n" "$TEST"
		false
	fi
done
