language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install libev-dev libssl-dev automake python-docutils flex bison

before_script:
  - ./bootstrap
  - make -j4

script:
  - make -j4 check VERBOSE=1

compiler:
  - clang
  - gcc
