#!/bin/sh

set -e
set -u

WORK_DIR=$(pwd)
ROOT_DIR=$(dirname "$0")

test -n "$ROOT_DIR"
cd "$ROOT_DIR"

mkdir -p build-aux
autoreconf -i

cd "$WORK_DIR"
"$ROOT_DIR"/configure \
	--enable-silent-rules \
	--enable-documentation \
	--with-lex \
	--with-yacc \
	"$@"
