#!/bin/bash
#
# Script that extracts the hitch.conf.example from an rst file and
# writes it to standard out. Most of this is copy-paste work from a
# script written by Lasse Karstensen.
#
# Author: Pål Hermunn Johansen <hermunn@varnish-software.com>
#

TMPFILE=$(mktemp)

cleanup() {
        rm -f "$TMPFILE"
        test -d "$VDIR" && rmdir "$VDIR"
}
trap cleanup EXIT

if [ ! -f "$1" ]; then
        echo "ERROR: Can't read $1"
        exit 1
fi

if [ -z "`grep ".. example-start" $1`" ]; then
        echo "No example marker in $1"
        exit 1
fi

echo "# Run 'man hitch.conf' for a descripion of all options." > $TMPFILE
sed -e '1,/^.. example-start/d' \
        -e '/.. example-end/,$d' \
        -e '/^[^ ]/d'  $1 >> $TMPFILE

sed -e ':a' -e 'N' -e '$!ba' -e 's/\n\n\n/\n\n/g' -e 's/\n    /\n/g' $TMPFILE
