version: 2.1

orbs:
  main: varnish/orb@0.0.8


parameters:
  src-commit:
    type: string
    default: "HEAD"
  pkg-commit:
    type: string
    default: "master"
  pkg-revision:
    type: string
    default: ""

workflows:
  build:
    jobs:
      - main/dist:
          docker-img: varnish/dist-vcp-almalinux-9
          src-commit: << pipeline.parameters.src-commit >>
          tarball-cmd: |
            dnf install -y libev-devel byacc flex python-docutils
            git checkout << pipeline.parameters.src-commit >>
            ./bootstrap
            make dist -j 16
      - main/tar-pkg-tools:
          fprint: "16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48"
          repo: pkg-hitch
          dir: .
          pkg-commit: << pipeline.parameters.pkg-commit >>
      - main/package:
          name: package-<< matrix.platform >>
          src-name: hitch
          pkg-revision: << pipeline.parameters.pkg-revision >>
          docker-pfx: varnish/pkg-hitch-
          requires:
            - main/dist
            - main/tar-pkg-tools
          matrix:
            parameters:
              platform:
                - ubuntu-focal
                - ubuntu-jammy
                - ubuntu-noble
                - debian-bookworm
                - debian-bullseye
                - debian-trixie
                - centos-7
                - almalinux-8
                - almalinux-9
                - rockylinux-8
                - amazonlinux-2023
      - main/collect-packages:
          requires:
            - main/package
